### ISSUE TITLE
Oneplus 5T: Camera not working on Android 11

### ISSUE THREAD

**Issue by Pietro395** [govizlora/optical-breacher#1]
[logcat_12-31-2020_10-38-20.txt](https://github.com/govizlora/optical-breacher/files/5756936/logcat_12-31-2020_10-38-20.txt)

I am using a custom rom based on android 11 on Oneplus 5T.

Using Chrome or Kiwi browser the camera does not load.

https://webrtc.github.io/samples/src/content/getusermedia/gum/
Using this test link the camera works fine

**Comment by govizlora** [comment]
Thanks! I'm currently trying to debug it using android emulator

**Comment by Pietro395** [comment]
> Thanks! I'm currently trying to debug it using android emulator

thank you! let me know if I can do something

**Comment by govizlora** [comment]
Could you help with https://github.com/govizlora/optical-breacher/issues/7 ? Thanks!!

**Comment by govizlora** [comment]
Is it fixed now? You can check https://govizlora.github.io/optical-breacher (v1.2)

**Comment by Pietro395** [comment]
> Is it fixed now? You can check https://govizlora.github.io/optical-breacher (v1.2)

I have to disable 'use native resolution' for it to work 😊
