### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by govizlora** [govizlora/optical-breacher#15]
We can add a favicon for the app. My current idea is to have something similar to a quick hack:
![image](https://user-images.githubusercontent.com/12785565/103468182-75b97700-4d0b-11eb-94f2-c2780e84b33e.png)

Contributions are welcomed!

**Comment by govizlora** [comment]
@rozmy Just want to pin you since you've mentioned it in another issue.

**Comment by jluo98** [comment]
I extracted the actual hack icons from the game and they look... well they don't look clean as a favicon. 
![actual hack icons](https://user-images.githubusercontent.com/8736917/103489428-1aa28580-4dda-11eb-8392-8215e51fc732.png)

So I remade the intelligence attribute icon in illustrator. 
![intelligence_256](https://user-images.githubusercontent.com/8736917/103489499-8d136580-4dda-11eb-975a-d7b893cdcc20.png)

You can get the SVG [here](https://drive.google.com/open?id=1VLuWC6nKyLr9Ji5iGEDcAO3RFdlTFnhr)

By the way, you can add the following code between `<head></head>` to make this page as an actual iOS web app to add to the home screen. It'll launch as if it were a standalone app. 
`<link rel="apple-touch-icon" href="icon.png">`
`<meta name="apple-mobile-web-app-capable" content="yes">`

**Comment by govizlora** [comment]
@Steve-luo I like this logo! Will add it to the app soon, thank you so much!

**Comment by rozmy** [comment]
That's a nice one. I was working on a quite similar version but we can use this. I'd add some visual representation of "Optical" to the icon, like camera lens, shutter blades or something.
![image](https://user-images.githubusercontent.com/7920792/103546027-b0094c80-4ea2-11eb-8178-8891354c41fe.png)

I made this as a scifi representation of all-seeing eye of god (an eye in a triangle shape)

**Comment by govizlora** [comment]
I like the small camera icon on browser tabs. It's simple, the yellow background means cyberpunk 2077 and the camera means it's optical.

For the large icon, I like the concept but still think it's a bit complicated as an icon. The triangle shape might instead work well inside the app as a dark-red icon in the header line's background. Maybe we should make it simpler with just the camera, or a surrounding shape like @Steve-luo 's. Also, I like the cyan shadow from the first design.

What do you guys think?

**Comment by town3r** [comment]
I like the idea of having the camera icon within @Steve-luo 's shadowed hexagon.

**Comment by rozmy** [comment]
This zip contains:
- 16x16 favicon.ico as fallback
- 128x128 favico.png for "modern browsers"
- Original version as png and svg for manifest.json
- New version with camera and a hexagon as png and svg for manifest.json

If you need any updates just let me know


[icons.zip](https://github.com/govizlora/optical-breacher/files/5777858/icons.zip)

**Comment by govizlora** [comment]
@all-contributors please add @rozmy and @Steve-luo for design

**Comment by govizlora** [comment]
@all-contributors please add @rozmy and @Steve-luo for design

**Comment by govizlora** [comment]
@all-contributors please add @Steve-luo for design

**Comment by govizlora** [comment]
@all-contributors please add @Steve-luo for design

**Comment by govizlora** [comment]
@all-contributors please add @Steve-luo for design
