### ISSUE TITLE
REQUEST: ShareX Custom File Uploader Config

### ISSUE THREAD

**Issue by Av-K47** [govizlora/optical-breacher#16]
Hi Chooms, 
                 This tool is pretty **GOSH DARN** incredible.
I am currently using ShareX to Custom Region Screenshot and Automatically copy the Cropped Image to the clipboard allowing me to Ctrl+V straight to the tool... But I was thinking maybe it could be even easier with the ShareX Custom File Uploader?
Where ShareX users could Custom Region Screenshot and it automatically Uploads to your tool... 

### Thing is I have no idea how to do this...

[https://getsharex.com/docs/custom-uploader](https://getsharex.com/docs/custom-uploader)
[https://github.com/ShareX/CustomUploaders](https://github.com/ShareX/CustomUploaders)

Might Shine some light on things, but I am a simpleton pleb who only knows how to code HTML from 1998...
If you could give it a whirl? It's a free tool to download @ [https://getsharex.com](https://getsharex.com/)

No biggie though... You have already done amazing work, and I Thank You **SO** much for even putting this out.
With great thanks, peace and love to you, Chooms,

_-Alvin_

**The example code I found off the ShareX github is:**

-------------------------------------------------

{
  "Version": "13.3.0",
  "Name": "Example",
  "DestinationType": "ImageUploader, TextUploader, FileUploader",
  "RequestMethod": "POST",
  "RequestURL": "https://example.com/upload.php",
  "Parameters": {
    "Parameter1": "Value1",
    "Parameter2": "Value2",
    "Parameter3": "Value3"
  },
  "Headers": {
    "Header1": "Value1",
    "Header2": "Value2",
    "Header3": "Value3"
  },
  "Body": "MultipartFormData",
  "Arguments": {
    "Argument1": "Value1",
    "Argument2": "Value2",
    "Argument3": "Value3"
  },
  "FileFormName": "file",
  "URL": "$json:url$",
  "ThumbnailURL": "$json:thumbnail_url$",
  "DeletionURL": "$json:deletion_url$",
  "ErrorMessage": "$json:error$"
}

-------------------------------------------------

**Comment by govizlora** [comment]
Hi, glad you like it! For the request to auto upload screenshot, currently I don't have the bandwidth to deal with it since the app still needs to be polished in terms of OCR accuracy and algorithm efficiency.

Btw, I did find some other cool desktop based hacking tools (but haven't tried) on reddit which seems more automatic when being used on a PC, maybe you can give it a try? https://www.reddit.com/r/cyberpunkgame/comments/kr19hj/i_wrote_a_script_to_automatically_complete_breach/?sort=qa

**Comment by Av-K47** [comment]
Totally understandable. It's pretty easy to do what I'm doing anyway. 
I just thought, maybe it could be even more easier.

Thanks for link, very cool. Will check it out.
Thanks for the reply!
