### ISSUE TITLE
Analyze from existing picture 

### ISSUE THREAD

**Issue by pierreantoine-cheron** [govizlora/optical-breacher#2]
REQUEST 
Can you please add an option to analyze from an existing picture. 
My auto focus is broken so I would like to take pictures manually and then load them in the website. 
Thank you for your amazing work!

**Comment by govizlora** [comment]
Yeah this is in the plan, thanks!

**Comment by rozmy** [comment]
If you need help on the UI, a new icon or something just drop me a line @govizlora

**Comment by marcusds** [comment]
This would be nice for just dropping in screenshots from PC.

**Comment by govizlora** [comment]
Solved by https://github.com/govizlora/optical-breacher/pull/14
Please open new tickets if it's not working well, thanks!
