### ISSUE TITLE
Infinite loop when solving this problem

### ISSUE THREAD

**Issue by ReagentX** [govizlora/optical-breacher#22]
![Untitled](https://user-images.githubusercontent.com/1920666/104968078-e969ae00-59b2-11eb-80dd-49304a37f4ad.png)

**Comment by govizlora** [comment]
Thanks! The current algorithm doesn't solve 7x7 matrix well (takes several seconds on PC and crashes on mobile). I'm planning to optimize it in the near future

**Comment by ReagentX** [comment]
It doesn’t work on PC either, it crashes Firefox.
