### ISSUE TITLE
Sequence with 5 characters not supported

### ISSUE THREAD

**Issue by MaBeuLux88** [govizlora/optical-breacher#30]
![image](https://user-images.githubusercontent.com/7153911/106691168-52683d00-65d3-11eb-8e39-797a229e8a32.png)

![image](https://user-images.githubusercontent.com/7153911/106691187-5dbb6880-65d3-11eb-91a2-c7185c417d11.png)

**Comment by govizlora** [comment]
I didn't know there there are targets with 5 characters, thank you! Fixed in https://github.com/govizlora/optical-breacher/commit/1f104b58ebebdd8c4c4cf149477fa58a8ce8afbf
![image](https://user-images.githubusercontent.com/12785565/107980187-afb9a200-6f74-11eb-9892-6b626b79b215.png)
