### ISSUE TITLE
Camera not working on Honor (Huawei) View10 running Android 9 

### ISSUE THREAD

**Issue by HexCodeHarry** [govizlora/optical-breacher#5]
I know older phone and OS but just thought I'd let you know I'm also having issues with the camera. Camera access granted in chrome but just black in target boxes and gives error if you try and scan.

**Comment by govizlora** [comment]
I just made some test cases in https://github.com/govizlora/optical-breacher/issues/7

**Comment by govizlora** [comment]
FIxed, see https://github.com/govizlora/optical-breacher/issues/7#issuecomment-753337104
