### ISSUE TITLE
Use Alexander's solver

### ISSUE THREAD

**Issue by rozmy** [govizlora/optical-breacher#6]
https://gitlab.com/alexanderrobertson/cyberpunk_breach_solver

**Comment by underlines** [comment]
or use that one, which allows to set buffer length:

https://github.com/kyle-rader/breach

**Comment by govizlora** [comment]
@underlines I think buffer length is also support here?
![image](https://user-images.githubusercontent.com/12785565/105303091-4eb6ce00-5b70-11eb-8829-1350c177f8bd.png)

**Comment by govizlora** [comment]
I checked the solver, seems it finds all the paths then evaluate them, which is very similar to what I'm currently doing. https://gitlab.com/alexanderrobertson/cyberpunk_breach_solver/-/blob/master/solver/solve.py#L103
