### ISSUE TITLE
For Android camera issues

### ISSUE THREAD

**Issue by govizlora** [govizlora/optical-breacher#7]
I tried to debug using Android Emulator but with no luck :(
I pushed some test cases and need your feedback for debugging. Could you try those below and tell me which works?

TEST 0: https://webrtc.github.io/samples/src/content/getusermedia/gum/ (It uses the front camera. If it doesn't work, there is little hope...)
TEST 1: https://govizlora.github.io/cyber/test1.html (Same as TEST 0, just moved to my site)
TEST 2: https://govizlora.github.io/cyber/test2.html (Using rear camera)
TEST 3: https://govizlora.github.io/cyber/test3.html (Specifying resolution...)
TEST 4: https://govizlora.github.io/cyber/test4.html (Pretty similar to the real app...)

**Comment by Pietro395** [comment]
TEST 0: **works**
TEST 1: **works**
TEST 2: **works**
TEST 3: does not work
TEST 4: does not work

Oneplus 5t Android 11

**Comment by govizlora** [comment]
Just merged a fix, people who only have issue with test 3 and 4 should be able to use the app now

**Comment by EliGuzman36** [comment]
Test 0 - Works
Test 1 - Works
Test 2 - Does not work
Test 3 - Works
Test 4 - Works

Galaxy S20+/Chrome/Android 11

The app was working earlier on this phone, but doesn't anymore on any browser. It does work on my LG V30 though.

**Comment by MrGray-1** [comment]
Test 0 - Works
Test 1 - Works
Test 2 - Does not work It says "getUserMedia error: NotReadableError"
Test 3 - Works
Test 4 - Works

Galaxy S20 Ultra 5G/Chrome/Android 11

Had been working just recently but just stopped working all of a sudden.

**Comment by VegettaPT** [comment]
Test 0/1 works
SAMSUNG Note 10+
ANDROID 10
The others don't work

**Comment by HexCodeHarry** [comment]
Honor View10 Android ver. 9
Test 0 - passed
Test 1 - passed
Test 2 - passed
Test 3 - failed
Test 4 - failed

**Comment by HexCodeHarry** [comment]
> Just merged a fix, people who only have issue with test 3 and 4 should be able to use the app now

Working on Honor View10 Thanks!

**Comment by govizlora** [comment]
Thanks for all of your feedbacks, they are very helpful! I just pushed v1.2 at https://govizlora.github.io/optical-breacher
For people who fails at Test 2 @EliGuzman36 @MrGray-1 your should enable `Use native resolution`.
And for people who fails after Test 3, you should disable `Use native resolution`.

**Comment by govizlora** [comment]
Closing this since no more replies recently, seems fixed. Please comment if there are still issues

**Comment by VVMaxVV** [comment]
Test 0 - Works
Test 1 - Does not work
Test 2 - Does not work
Test 3 - Does not work
Test 4 - Does not work

Galaxy A50/Chrome/Android 10

Error: NotAllowedError. Native resolution dont help

**Comment by govizlora** [comment]
@VVMaxVV This is weird since Test 0 and 1's webpages are identical... Could it be you accidentally disabled camera access for https://govizlora.github.io ? You can reset it here: https://support.google.com/chrome/answer/114662?co=GENIE.Platform%3DAndroid&hl=en-GB

**Comment by lukejames1111** [comment]
Test 0 - Does not work
Test 1 - Does not work
Test 2 - Does not work
Test 3 - Does not work
Test 4 - Does not work

Pixel 3XL/Chrome/Android 11

**Comment by VVMaxVV** [comment]
> @VVMaxVV This is weird since Test 0 and 1's webpages are identical... Could it be you accidentally disabled camera access for https://govizlora.github.io ? You can reset it here: https://support.google.com/chrome/answer/114662?co=GENIE.Platform%3DAndroid&hl=en-GB

Oh, you were right, I must have inadvertently denied permission.  Everything is ok, but in some places the camera does not read accurately and there is not enough manual change.  But thank you very much <3

**Comment by govizlora** [comment]
> Test 0 - Does not work
> Test 1 - Does not work
> Test 2 - Does not work
> Test 3 - Does not work
> Test 4 - Does not work
> 
> Pixel 3XL/Chrome/Android 11

If test 0 doesn't work, it usually means the entire webRTC feature is disabled from your phone. My suggestion is to check the privacy / permission settings on your phone, maybe you have disabled camera access for browsers completely.

**Comment by AureliusKing** [comment]
Test 0: works 
Test 1 : does not work 
Test 2: does not work
Test 3: does not work
Test 4: does not work

One Plus 8 Pro

**Comment by govizlora** [comment]
> Test 0: works
> Test 1 : does not work
> Test 2: does not work
> Test 3: does not work
> Test 4: does not work
> 
> One Plus 8 Pro

Can you check if https://github.com/govizlora/optical-breacher/issues/7#issuecomment-760410456 applies to your case?

**Comment by AureliusKing** [comment]
> > Test 0: works
> > Test 1 : does not work
> > Test 2: does not work
> > Test 3: does not work
> > Test 4: does not work
> > One Plus 8 Pro
> 
> Can you check if [#7 (comment)](https://github.com/govizlora/optical-breacher/issues/7#issuecomment-760410456) applies to your case?

Thx that helped :)
